[package]
name = "crowbar"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]

[dependencies]
hyper = "0.7.2"
git2 = "0.3.4"
mdo = "0.2.0"
walkdir = "0.1.5"
serde = "0.6.11"
serde_macros = "0.6.11"
serde_json = "0.6.0"
semver = "0.2.2"
wrapped_enum = "0.1.3"