[package]
name = "crowbar"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
hyper = "0.9.6"
git2 = "0.4.3"
mdo = "0.2.0"
walkdir = "0.1.5"
serde = "0.7.8"
serde_macros = "0.7.8"
serde_json = "0.7.1"
semver = "0.2.3"
wrapped_enum = "0.1.3"
